services:
  scm-service:
    build: .
    ports:
      - "8080:8080"
    container_name: scm-service
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - scm-network

  redis:
    image: redis:7.2-alpine
    container_name: scm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - scm-network

networks:
  scm-network:
    driver: bridge

volumes:
  redis-data:
