apiVersion: apps/v1
kind: Deployment
metadata:
  name: scm-service
  labels:
    app: scm-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scm-service
  template:
    metadata:
      labels:
        app: scm-service
    spec:
      containers:
      - name: scm-service
        image: scm-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"