{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scm-service.fullname" . }}-redis
  labels:
    {{- include "scm-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  selector:
    {{- include "scm-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
  - port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.port }}
  type: ClusterIP
{{- end }}